import { hash } from "bcryptjs";
import { NextRequest, NextResponse } from "next/server";
import prisma  from "@/core/lib/prisma"

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { username, email, password } = body;

    // Field required validation
    if (!username || !email || !password) {
      return NextResponse.json({ message: "Missing fields" }, { status: 400 });
    }

    // Encrypting the password using bcrypt hash function
    const hashedPassword = await hash(password, 10);
    // creating the user user prisma.user.create
    const user = await prisma.user.create({
      data: {
        username,
        email,
        password: hashedPassword,
        role: "STUDENT", // Explicitly set role; super admin can change the role afterwards
        isVerified: false, // Default until approved by super admin
      },
    });
    // success response
    console.log(user)
    return NextResponse.json(user, { status: 201 });
  } catch (error: any) {
    console.log(error)
    // Handle unique constraint violation (email/username), P2002 is a code generated by prisma
    if (error.code === "P2002") {
      return NextResponse.json(
        { error: "Username or email already exists" },
        { status: 409 }
      );
    }
    // Internal server error
    return NextResponse.json(
      { error: "Failed to create user" },
      { status: 500 }
    );
  }
}





// import { hash } from "bcryptjs";
// import { NextRequest, NextResponse } from "next/server";
// import prisma from "@/core/lib/prisma";

// export async function POST(req: NextRequest) {
//   try {
//     const { username, email, password } = await req.json();

//     if (!username || !email || !password) {
//       return NextResponse.json(
//         { error: "All fields are required" },
//         { status: 400 }
//       );
//     }

//     const hashedPassword = await hash(password, 10);

//     const user = await prisma.user.create({
//       data: {
//         username,
//         email,
//         password: hashedPassword,
//         role: "STUDENT",
//         isVerified: false,
//       },
//     });

//     return NextResponse.json(
//       {
//         id: user.id,
//         username: user.username,
//         email: user.email,
//         role: user.role,
//       },
//       { status: 201 }
//     );
//   } catch (error: any) {
//     console.error("SIGNUP ERROR:", error);

//     if (error?.code === "P2002") {
//       return NextResponse.json(
//         { error: "Username or email already exists" },
//         { status: 409 }
//       );
//     }

//     return NextResponse.json(
//       { error: "Failed to create user" },
//       { status: 500 }
//     );
//   }
// }
