import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/core/providers/Auth-provider";
import { Toaster } from "sonner";


const outfit =  Outfit({
  weight:['300','400','600','700','800','900'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className}  antialiased`}
      >
        <AuthProvider>
           {children}
        </AuthProvider>
       <Toaster/>
      </body>
    </html>
  );
}
